const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.AJAX,
		C3.Plugins.Arr,
		C3.Plugins.AdvancedRandom,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.LocalStorage,
		C3.Plugins.Timeline,
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Plugins.DrawingCanvas,
		C3.Behaviors.Physics,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Plugins.TextBox,
		C3.Plugins.TiledBg,
		C3.Behaviors.Flash,
		C3.Behaviors.Anchor,
		C3.Plugins.Spritefont2,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Fade,
		C3.Plugins.Dictionary,
		C3.Behaviors.EightDir,
		C3.Plugins.Json,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.projectname,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.LoadLayoutTextures,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Timeline.Cnds.OnTimelineFinishedByTags,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Exps.imageloadingprogress,
		C3.Plugins.Audio.Cnds.PreloadsComplete,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.len,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.TextBox.Acts.SetPos,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.AJAX.Cnds.OnError,
		C3.Plugins.Browser.Acts.Alert,
		C3.Plugins.Timeline.Acts.SetInstance,
		C3.Plugins.Timeline.Acts.PlayTimeline,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.IsPreview,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Behaviors.Physics.Acts.SetFriction,
		C3.Behaviors.Physics.Acts.SetElasticity,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Behaviors.Physics.Acts.ApplyImpulseToward,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Physics.Cnds.IsEnabled,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Behaviors.Physics.Exps.VelocityY,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Spritefont2.Exps.UID,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Spritefont2.Acts.SetX,
		C3.Plugins.TiledBg.Exps.BBoxRight,
		C3.Plugins.Spritefont2.Exps.Width,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.Dictionary.Cnds.HasKey,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Spritefont2.Acts.SetEffectParam,
		C3.Plugins.Sprite.Exps.ColorValue,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Spritefont2.Exps.X,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Exps.lowercase,
		C3.Plugins.Timeline.Cnds.IsPlayingByTags,
		C3.Plugins.Sprite.Exps.ObjectTypeName,
		C3.Plugins.Spritefont2.Cnds.PickByUID,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.System.Exps.rgba,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Json.Exps.ArraySize,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.System.Exps.left
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{Keyboard: 0},
	{AJAX: 0},
	{aWords: 0},
	{Rnd: 0},
	{Audio: 0},
	{Browser: 0},
	{LocalStorage: 0},
	{TC: 0},
	{TLReferencePop: 0},
	{Name: 0},
	{Color: 0},
	{Mouse: 0},
	{DEBUGDraw: 0},
	{Basket: 0},
	{NetFront: 0},
	{Active: 0},
	{Scored: 0},
	{Destroy: 0},
	{HitRim: 0},
	{Physics: 0},
	{Tween: 0},
	{Ball: 0},
	{bgCourt: 0},
	{Bar: 0},
	{bgGame: 0},
	{Ring: 0},
	{Side: 0},
	{Ground: 0},
	{BallSpawner: 0},
	{Destroyer: 0},
	{Score: 0},
	{NetWall: 0},
	{NetBack: 0},
	{Enter: 0},
	{LimitBar: 0},
	{LimitBasket: 0},
	{FallLimit: 0},
	{GroundOverlap: 0},
	{Enabled: 0},
	{Sine: 0},
	{Sine2: 0},
	{btStart: 0},
	{Logo: 0},
	{BallLogo: 0},
	{BasketMenu: 0},
	{bgIntro: 0},
	{btMode: 0},
	{btLeaderboard: 0},
	{btLeaderboard1: 0},
	{Review_input: 0},
	{Review_name: 0},
	{Loading_txt: 0},
	{btHome: 0},
	{UnitWidth: 0},
	{Flash: 0},
	{LivesBar: 0},
	{Anchor: 0},
	{LivesEmptyBar: 0},
	{btAudio: 0},
	{btClose: 0},
	{btInfo: 0},
	{btReplay: 0},
	{txScore: 0},
	{MoveTo: 0},
	{Fade: 0},
	{txVFX: 0},
	{wndInfo: 0},
	{wndResult: 0},
	{Tag: 0},
	{Label: 0},
	{LifeMessage: 0},
	{txGoals: 0},
	{LabelTitle: 0},
	{Template: 0},
	{LabelLevel: 0},
	{wndLevel: 0},
	{btNext: 0},
	{vfxGoal: 0},
	{cursor: 0},
	{dConfig: 0},
	{dLevels: 0},
	{Review_bg: 0},
	{"8Direction": 0},
	{Loading: 0},
	{txt_welcome: 0},
	{txt_best_score: 0},
	{welcome_next: 0},
	{Data: 0},
	{txtError: 0},
	{ok_txt_bg: 0},
	{ok_txt: 0},
	{Error_bg: 0},
	{pnlLeaderboard: 0},
	{txLeaderboard: 0},
	{txLeaderboardTitle: 0},
	{Bg_Leaderboard: 0},
	{home_leaderboard: 0},
	{board_loading: 0},
	{board_err_bg: 0},
	{board_refresh: 0},
	{board_err_msg: 0},
	{board_err_home: 0},
	{JSON: 0},
	{Text: 0},
	{rev_fade: 0},
	{JSON2: 0},
	{JSON3: 0},
	{FAEntrance: 0},
	{FASF: 0},
	{FAPop: 0},
	{FButton: 0},
	{FLivesBar: 0},
	{FUI: 0},
	{FTarget: 0},
	{FNet: 0},
	{count: 0},
	{xN: 0},
	{yN: 0},
	{d: 0},
	{thick: 0},
	{ang: 0},
	{a: 0},
	{aIn: 0},
	{aGoal: 0},
	{tween: 0},
	{y1: 0},
	{x1: 0},
	{y2: 0},
	{x2: 0},
	{index: 0},
	{tMax: 0},
	{targetX: 0},
	{targetY: 0},
	{enable: 0},
	{next: 0},
	{lvl: 0},
	{bar: 0},
	{basket: 0},
	{pBasket: 0},
	{pBar: 0},
	{magBar: 0},
	{magBasket: 0},
	{randomBar: 0},
	{randomBasket: 0},
	{bMag: 0},
	{bMag2: 0},
	{bPeriod: 0},
	{bPeriod2: 0},
	{bRandom: 0},
	{bRandom2: 0},
	{s: 0},
	{value: 0},
	{win: 0},
	{x: 0},
	{y: 0},
	{text: 0},
	{color: 0},
	{message: 0},
	{name: 0},
	{setActive: 0},
	{activeLayersList: 0},
	{uid: 0},
	{UID: 0},
	{DEBUG: 0},
	{Mode: 0},
	{Lives: 0},
	{Goals: 0},
	{Level: 0},
	{Target: 0},
	{ScaleDensityRatio: 0},
	{ActiveLayers: 0},
	{SEPLayers: 0},
	{HighScore: 0},
	{TotalFileCount: 0},
	{LoadedFileCount: 0},
	{Volume: 0},
	{VolumeMusic: 0},
	{TAGLoad: 0},
	{AJXConfig: 0},
	{AJXLevels: 0},
	{TAGScale: 0},
	{AUDSfx: 0},
	{AUDMusic: 0},
	{AUDUI: 0},
	{LSHighScore: 0},
	{LSLevel: 0},
	{LBLScore: 0},
	{LBLGoals: 0},
	{LBLHighScore: 0},
	{LBLLives: 0},
	{TLInfo: 0},
	{TLPrefix: 0},
	{TLLifeMessage: 0},
	{MODELevels: 0},
	{MODEEndless: 0},
	{BallRising: 0},
	{BallNone: 0},
	{BallFalling: 0},
	{DTolerance: 0},
	{DClampInputX: 0},
	{DGravity: 0},
	{DThrowForce: 0},
	{DBallSmallScale: 0},
	{DBallNormalScale: 0},
	{DBallThrowScale: 0},
	{DThrowAngle: 0},
	{DBallScaleDuration: 0},
	{DLives: 0},
	{DLevels: 0},
	{DFlashTime: 0},
	{DFlashCountLives: 0},
	{DVolumeSfx: 0},
	{DVolumeMusic: 0},
	{DBallFriction: 0},
	{DBallElasticity: 0},
	{DRingFriction: 0},
	{DRingElasticity: 0},
	{DNetFriction: 0},
	{DNetElasticity: 0},
	{DGroundFriction: 0},
	{DGroundElasticity: 0},
	{DGoalScore: 0},
	{DGoalScorePerfect: 0},
	{DWaitLevel: 0},
	{DMovePeriodBase: 0},
	{DMoveMagnitudeBase: 0},
	{DMoveRandomBase: 0},
	{DMovePeriodPercentage: 0},
	{DMoveMagnitudePercentage: 0},
	{DMoveRandomPercentage: 0},
	{DBasketFactor: 0},
	{DBarFactor: 0},
	{DLevelStartMoving: 0},
	{DTargetVoefficientPrefix: 0},
	{TemplateReplace: 0},
	{Nickname: 0},
	{APIBase: 0},
	{UserID: 0},
	{PreviousScore: 0},
	{LoginDone: 0},
	{LeaderBoardData: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	aWords: class extends self.IArrayInstance {},
	Rnd: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	TC: class extends self.IInstance {},
	TLReferencePop: class extends self.ISpriteInstance {},
	Color: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	DEBUGDraw: class extends self.IDrawingCanvasInstance {},
	Basket: class extends self.ISpriteInstance {},
	NetFront: class extends self.ISpriteInstance {},
	Ball: class extends self.ISpriteInstance {},
	bgCourt: class extends self.ISpriteInstance {},
	Bar: class extends self.ISpriteInstance {},
	bgGame: class extends self.ISpriteInstance {},
	Ring: class extends self.ISpriteInstance {},
	Ground: class extends self.ISpriteInstance {},
	BallSpawner: class extends self.ISpriteInstance {},
	Destroyer: class extends self.ISpriteInstance {},
	Score: class extends self.ISpriteInstance {},
	NetWall: class extends self.ISpriteInstance {},
	NetBack: class extends self.ISpriteInstance {},
	Enter: class extends self.ISpriteInstance {},
	LimitBar: class extends self.ISpriteInstance {},
	LimitBasket: class extends self.ISpriteInstance {},
	FallLimit: class extends self.ISpriteInstance {},
	GroundOverlap: class extends self.ISpriteInstance {},
	btStart: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	BallLogo: class extends self.ISpriteInstance {},
	BasketMenu: class extends self.ISpriteInstance {},
	bgIntro: class extends self.ISpriteInstance {},
	btMode: class extends self.ISpriteInstance {},
	btLeaderboard: class extends self.ISpriteInstance {},
	btLeaderboard1: class extends self.ITextInstance {},
	Review_input: class extends self.ITextInputInstance {},
	Review_name: class extends self.ITextInstance {},
	Loading_txt: class extends self.ITextInstance {},
	btHome: class extends self.ISpriteInstance {},
	LivesBar: class extends self.ITiledBackgroundInstance {},
	LivesEmptyBar: class extends self.ITiledBackgroundInstance {},
	btAudio: class extends self.ISpriteInstance {},
	btClose: class extends self.ISpriteInstance {},
	btInfo: class extends self.ISpriteInstance {},
	btReplay: class extends self.ISpriteInstance {},
	txScore: class extends self.ISpriteFontInstance {},
	txVFX: class extends self.ISpriteFontInstance {},
	wndInfo: class extends self.ISpriteInstance {},
	wndResult: class extends self.ISpriteInstance {},
	Label: class extends self.ISpriteFontInstance {},
	Fade: class extends self.ISpriteInstance {},
	LifeMessage: class extends self.ISpriteInstance {},
	txGoals: class extends self.ISpriteFontInstance {},
	LabelTitle: class extends self.ISpriteFontInstance {},
	LabelLevel: class extends self.ISpriteFontInstance {},
	wndLevel: class extends self.ISpriteInstance {},
	btNext: class extends self.ISpriteInstance {},
	vfxGoal: class extends self.ISpriteInstance {},
	cursor: class extends self.ISpriteInstance {},
	dConfig: class extends self.IDictionaryInstance {},
	dLevels: class extends self.IDictionaryInstance {},
	Review_bg: class extends self.ISpriteInstance {},
	Loading: class extends self.ISpriteInstance {},
	txt_welcome: class extends self.ITextInstance {},
	txt_best_score: class extends self.ITextInstance {},
	welcome_next: class extends self.ISpriteInstance {},
	Data: class extends self.ISpriteInstance {},
	txtError: class extends self.ITextInstance {},
	ok_txt_bg: class extends self.ISpriteInstance {},
	ok_txt: class extends self.ITextInstance {},
	Error_bg: class extends self.ISpriteInstance {},
	pnlLeaderboard: class extends self.ISpriteInstance {},
	txLeaderboard: class extends self.ITextInstance {},
	txLeaderboardTitle: class extends self.ITextInstance {},
	Bg_Leaderboard: class extends self.ISpriteInstance {},
	home_leaderboard: class extends self.ISpriteInstance {},
	board_loading: class extends self.ITextInstance {},
	board_err_bg: class extends self.ISpriteInstance {},
	board_refresh: class extends self.ISpriteInstance {},
	board_err_msg: class extends self.ITextInstance {},
	board_err_home: class extends self.ISpriteInstance {},
	JSON: class extends self.IJSONInstance {},
	Text: class extends self.ITextInstance {},
	rev_fade: class extends self.ISpriteInstance {},
	JSON2: class extends self.IJSONInstance {},
	JSON3: class extends self.IJSONInstance {},
	FAEntrance: class extends self.ISpriteInstance {},
	FASF: class extends self.ISpriteFontInstance {},
	FAPop: class extends self.ISpriteInstance {},
	FButton: class extends self.ISpriteInstance {},
	FLivesBar: class extends self.ITiledBackgroundInstance {},
	FUI: class extends self.ISpriteInstance {},
	FTarget: class extends self.ISpriteInstance {},
	FNet: class extends self.ISpriteInstance {}
}